<a href="https://colab.research.google.com/github/ibonetc/IA_EIA_Optativa/blob/main/Heur%C3%ADstica_AlgoritmosB%C3%BAsqueda/AG_Knacksack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmo genético para el problema de la mochila

In [50]:
import numpy as np
import pandas as pd

In [51]:
# @title Introduzca los valores de Cantidad de productos (N) y Peso en kg (W) de la mochila
N = 10 # @param {type:"integer"}
W = 15 # @param {type:"integer"}
minprice= 1 # @param {type:"number"}
maxprice= 100 # @param {type:"number"}
NP= 30 # @param {type:"integer"}


Generar precios y pesos aleatoreamente

In [52]:
weights=W*np.random.random_sample(N)
prices=(maxprice-minprice)*np.random.random_sample(N)+minprice
print(weights)
print(prices)

[ 9.10046136  0.90689865  0.47414162  0.25002241  5.68044529  4.25619432
  1.01914364 10.8294899   3.09272839  3.35059471]
[31.88411311 14.21248782 38.35745268 85.2711279  84.95001941 86.76284257
 81.88415725 83.33086737 85.43222503 72.96600308]


In [53]:
ind1=np.random.randint(0,2,N)
ind1

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1])

## Función de validación

In [54]:
def valid(ind):
  return 0<sum(ind*weights)<=W

## Generar primera población

In [55]:
def generateFirstPopulation(N,NP):
  population=[]
  count=0;
  while True:
    ind=np.random.randint(0,2,N)
    if (valid(ind)):
      population.append(ind)
      count=count+1
    if count==NP:
      return population

In [56]:
population=generateFirstPopulation(N,NP)
population

[array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1]),
 array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1]),
 array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 1, 0, 0, 1, 1]),
 array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0]),
 array([0, 1, 1, 1, 1, 1, 0, 0, 0, 1]),
 array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1]),
 array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0]),
 array([0, 1, 1, 1, 1, 1, 1, 0, 0, 0]),
 array([0, 1, 1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 0, 1]),


## Función fitness

In [57]:
def fitnessFunc(ind):
  return sum(ind*prices)

## Método de la ruleta

In [58]:
sampleP=generateFirstPopulation(N,5)
print(sampleP)
f=[fitnessFunc(x) for x in sampleP]
print(f)
probability=f/sum(f)
print(probability)
accumProb=np.cumsum(probability)

[array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0]), array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 1, 0, 1, 1]), array([0, 1, 1, 0, 1, 0, 0, 0, 0, 1]), array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0])]
[266.79999800571386, 171.21689617036157, 278.63983804293207, 210.4859629837329, 254.07922485261628]
[0.2258678  0.14494897 0.23589118 0.17819341 0.21509864]


In [59]:
df=pd.DataFrame(list(zip(sampleP,f,probability,accumProb)),columns=['Cromosoma','Fitness','Probabilidad','Prob_Acumulada'])
df

Cromosoma     Fitness  Probabilidad  Prob_Acumulada
0  [0, 1, 0, 1, 0, 0, 1, 0, 1, 0]  266.799998      0.225868        0.225868
1  [1, 1, 1, 0, 0, 1, 0, 0, 0, 0]  171.216896      0.144949        0.370817
2  [0, 0, 1, 0, 0, 0, 1, 0, 1, 1]  278.639838      0.235891        0.606708
3  [0, 1, 1, 0, 1, 0, 0, 0, 0, 1]  210.485963      0.178193        0.784901
4  [0, 0, 0, 0, 0, 1, 1, 0, 1, 0]  254.079225      0.215099        1.000000

In [60]:
import plotly.graph_objects as go
fig=go.Figure(data=[go.Pie(labels=np.arange(5), values=f)])
fig.show()

In [61]:
def roulette(population):
  f=[fitnessFunc(x) for x in population]
  probability=f/sum(f)
  accumProb=np.cumsum(probability)
  return accumProb

## Operador de selección

In [62]:
nr=np.random.uniform()
nr

0.9692577696179181

In [63]:
def selection(population):
  nr=np.random.uniform()
  for i, p in enumerate(accumProb):
    if nr<p:
      return (i, population[i])

In [64]:
selection(population)

(1, array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]))